import { GoogleGenerativeAI } from "@google/generative-ai";

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

// Initialize Gemini
// Note: If API_KEY is missing, this might throw or fail later.
// We'll handle it inside the function.
const genAI = API_KEY ? new GoogleGenerativeAI(API_KEY) : null;

export const generateProductDescription = async (prompt) => {
  if (!genAI) {
    console.warn("Gemini API Key is missing.");
    return "Sample product description generated by AI (Placeholder). Please configure VITE_GEMINI_API_KEY.";
  }
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error("Error generating description:", error);
    return "Error generating description. Please try again.";
  }
};

export const generateProductImage = async (prompt) => {
  if (!genAI) {
    console.warn("Gemini API Key is missing.");
    return `https://placehold.co/500x500?text=${encodeURIComponent('No API Key')}`;
  }
  try {
    const model = genAI.getGenerativeModel({
      model: "gemini-2.0-flash-exp",
      generationConfig: {
        responseModalities: ["Text", "Image"],
      },
    });
    const result = await model.generateContent(prompt);
    const parts = result.response.candidates[0].content.parts;
    for (const part of parts) {
      if (part.inlineData) {
        const { data, mimeType } = part.inlineData;
        return `data:${mimeType};base64,${data}`;
      }
    }
    throw new Error('No image returned by the model');
  } catch (error) {
    console.error("Error generating image:", error);
    throw error;
  }
};
